name: Testing Mysqlbinlog Sync

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9
    services:
      mysql8036_1:
        image: shinhwagk/mysql:8.0.36
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_MYSQLD_ARGS: "--server-id=1000 --log-bin=mysql-bin --binlog-format=ROW --gtid-mode=on --enforce-gtid-consistency=on --binlog-rows-query-log-events=on --binlog-row-image=FULL --max-connections=5000 --innodb-flush-log-at-trx-commit=0 --sync-binlog=0 --binlog-row-metadata=FULL"
        ports:
          - 33061:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mysql8036_2:
        image: shinhwagk/mysql:8.0.36
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_MYSQLD_ARGS: "--server-id=1001 --log-bin=mysql-bin --binlog-format=ROW --gtid-mode=on --enforce-gtid-consistency=on --binlog-rows-query-log-events=on --binlog-row-image=FULL --max-connections=5000 --innodb-flush-log-at-trx-commit=1 --sync-binlog=1 --binlog-row-metadata=FULL --slave-parallel-workers=1"
        ports:
          - 33062:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mysql8036_3:
        image: shinhwagk/mysql:8.0.36
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_MYSQLD_ARGS: "--server-id=1001 --log-bin=mysql-bin --binlog-format=ROW --gtid-mode=on --enforce-gtid-consistency=on --binlog-rows-query-log-events=on --binlog-row-image=FULL --max-connections=5000 --innodb-flush-log-at-trx-commit=1 --sync-binlog=1 --binlog-row-metadata=FULL --slave-parallel-workers=1"
        ports:
          - 33063:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init container
        run: bash initContainer.sh
      - run:
          ps -ef 
          ss -lnpt

      - name: Connect to MySQL and run a query
        run: |
          for _ in `seq 1 10`; do
            # mysqladmin ping -h127.0.0.1 -P33061 -proot_password -uroot
            mysqladmin ping -hmysql8036_1 -P33061 -proot_password -uroot
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Running testing
        run: |
          set -e
          bash initMysql.sh

 